IKT201-G 24H Internettjenester/assignment_3/Models/ErrorViewModel.cs
namespace assignment_3.Models;

public class ErrorViewModel{
    public string? RequestId{ get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

IKT201-G 24H Internettjenester/assignment_3/Models/Guest.cs
using System.ComponentModel.DataAnnotations;

namespace assignment_3.Models;

public class Guest{
    
    public int Id{ get; set; }
    
    [Required]
    public string Name{ get; set; } = String.Empty;
    
    [Required] [MinLength(5)] [MaxLength(50)]
    public string Title{ get; set; } = String.Empty;
    
    [Required] [MinLength(20)] [MaxLength(200)]
    public string Message{ get; set; } = String.Empty;

    public Guest(){}
    public Guest(string name, string title, string message){
        Name = name;
        Title = title;
        Message = message;
    }

}

IKT201-G 24H Internettjenester/assignment_3/Controllers/GuestbookController.cs
using assignment_3.Models;
using assignment_3.Data;
using Microsoft.AspNetCore.Mvc;

namespace assignment_3.Controllers;

public class GuestbookController : Controller{

    // For local use. Wil be interface for global db
    private readonly ApplicationDbContext _db;
    
    
    public GuestbookController(ApplicationDbContext db){
        // Retrieved reference to global db
        _db = db;
    }

    [HttpGet]
    public IActionResult Index(){
        var guests = _db.Guests.ToList();
        return View(guests);
    }
    
    [HttpGet]
    public IActionResult Add(){
        return View();
    }
    
    [HttpPost]
    public IActionResult Add(Guest guest){
        
        if (!ModelState.IsValid)
            return View(guest);
        
        _db.Guests.Add(guest);
        _db.SaveChanges();
        
        return RedirectToAction(nameof(Index));
    }
}

IKT201-G 24H Internettjenester/assignment_3/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using assignment_3.Models;

namespace assignment_3.Controllers;

public class HomeController : Controller{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger){
        _logger = logger;
    }

    public IActionResult Index(){
        return View();
    }

    public IActionResult Privacy(){
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error(){
        return View(new ErrorViewModel{ RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

IKT201-G 24H Internettjenester/assignment_3/Views/Guestbook/Add.cshtml
@model Guest
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<!DOCTYPE html>

<html lang="en">
<head>
    <title>title</title>
</head>
<body>
<div>
      
    <form method="post" class="form-control">
        <label asp-for="Name"></label>
        <input id="Name" asp-for="Name" required="required" class="form-control"/>
        <span asp-validation-for="Name"></span>
        <br/>
        
        <label asp-for="Title"></label>
        <input id="Title" asp-for="Title" required="required" minlength="5" maxlength="50" class="form-control"/>
        <span asp-validation-for="Title"></span>
        <br/>
        
        <label asp-for="Message"></label>
        <textarea id="Message" asp-for="Message" required="required" minlength="20" maxlength="200" class="form-control"></textarea>
        <span asp-validation-for="Message"></span>
        <br/>
        
        <input type="submit" id="Submit" value="Add Guest" class="btn btn-primary"/>
    </form>

    
    
</div>
</body>
</html>

IKT201-G 24H Internettjenester/assignment_3/Views/Guestbook/Index.cshtml
@model IEnumerable<Guest>
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      <ul class="list-group">
          @foreach (var guest in Model){
              <li class="list-group-item">@guest.Name @guest.Title @guest.Message</li>
          }
      </ul>
</div>
</body>
</html>

IKT201-G 24H Internettjenester/assignment_3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IKT201-G 24H Internettjenester/assignment_3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - assignment_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/assignment_3.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">assignment_3</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guestbook" asp-action="Index">Guest Index</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guestbook" asp-action="Add">Add guest</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - assignment_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>